# 不带参数的层

In [18]:
import torch 
import torch.nn.functional as F 
from torch import nn  

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [19]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [20]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [21]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-9.3132e-09, grad_fn=<MeanBackward0>)

# 带参数的图层

In [22]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units, ))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data 
        return F.relu(linear)

In [23]:
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 1.7316,  1.0210, -0.3408],
        [-0.5556,  0.0450,  2.5071],
        [-0.2388, -0.1171, -0.7854],
        [ 0.1685, -0.9019, -0.0049],
        [-0.1384, -0.6513, -1.3126]], requires_grad=True)

In [24]:
dense(torch.rand(2, 5))

tensor([[1.5884, 0.5041, 0.0000],
        [0.7175, 0.1730, 0.0000]])

In [28]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[4.5767],
        [4.3042]])