In [8]:
!nvidia-smi

'nvidia-smi' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


# 计算设备

In [9]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x1ef2b9d2580>)

In [10]:
torch.cuda.device_count()

1

In [11]:
def try_gpu(i=0):  #@save
    """如果存在，则返回gpu(i)，否则返回cpu()。"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]。"""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

# 张量与gpu 

In [12]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [13]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [17]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y, Y.device

(tensor([[0.7633, 0.5670, 0.5973],
         [0.0465, 0.2470, 0.3385]]),
 device(type='cpu'))

In [21]:
Z = X.cuda(0)
Y = torch.rand(2, 3, device=try_gpu(0))
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [22]:
Y + Z

tensor([[1.5086, 1.9658, 1.4048],
        [1.9775, 1.4825, 1.4214]], device='cuda:0')

In [24]:
Z.cuda(0) is Z

True

# 神经网络与GPU

In [25]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [26]:
net(X)

tensor([[0.5815],
        [0.5815]], device='cuda:0', grad_fn=<AddmmBackward>)

In [27]:
net[0].weight.data.device

device(type='cuda', index=0)